name: Docker Build and Push

on:
  push:
    branches:
      - main  # 可以改为你需要触发的分支，例如 master 或其他分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Docker Buildx (需要此步骤以支持构建多平台的镜像)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # 登录到 Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # 存储 Docker Hub 用户名的 GitHub 密钥
        password: ${{ secrets.DOCKER_PASSWORD }}  # 存储 Docker Hub 密码或 Token 的 GitHub 密钥

    # 构建 Docker 镜像
    - name: Build Docker image
      run: |
        docker build -t your-dockerhub-username/your-image-name:latest .

    # 推送 Docker 镜像到 Docker Hub
    - name: Push Docker image
      run: |
        docker push your-dockerhub-username/your-image-name:latest

