name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # 选择在推送到 master 分支时触发构建和推送操作
    tags:
      - 'v*'  # 也可以在你创建标签时触发

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 Ubuntu 环境

    steps:
      # 1. Check out the code
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Set up Docker Buildx (用于支持多平台构建，可选)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ddph
          password: dph970628

      # 4. Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ddph/dph:latest .

      # 5. Push the Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push ddph/dph:latest

